spring:
  data:
    cassandra:
      keyspace-name: bookings
      port: 9042
      local-datacenter: datacenter1
      contact-points: localhost

app:
  database:
    sequence:
        id:
          start-value: 957000001


external:
  bookings:
    availability-check:
      api:
        endpoint: https://maersk.com/api/bookings/checkAvailable

